# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

# Aliases are shorthand references for common settings.
aliases:
  # Cache Management
  - &restore-node-modules
      keys:
        - v2-node-modules-{{ checksum "package.json" }}
  - &save-node-modules
      paths:
        - node_modules
      key: v2-node-modules-{{ checksum "package.json" }}

  # Branch Filtering
  - &filter-only-master
    branches:
      only:
        - master
  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

# Job definitions. Job execution is orchestrated in the 'workflows' section.
jobs:
  build_spa:
    docker:
      - image: circleci/node:8
    steps:
      - checkout 
      - run:
          name: Configure build environment
          command: sh ./configure_build_env.sh
      - restore_cache: *restore-node-modules
      - run: 
          name: Install SPA packages
          command: yarn install
      - save_cache: *save-node-modules
#      - run: 
#          name: Test SPA app
#          command: yarn test -w 1 --coverage
      - run: 
          name: Configure build parameters
          command: cp .env.$BUILD_ENV .env.local
      - run: 
          name: Build SPA app
          command: yarn build
# Job orchestration
workflows:
  version: 2
  # Build and test the code on every commit. 
  # Publish the style guide on successful build/test of master.
  build-and-publish:
    jobs:
      - build_spa:
          filters: *filter-ignore-gh-pages
